- hosts: all
  tasks:
    - name: stop container
      shell: docker container stop HED-container
      ignore_errors: true
    - name: remove container
      shell: docker container rm HED-container
      ignore_errors: true
    - name: remove image
      shell: docker image rm houssamed100/docker-project
      ignore_errors: true
    - name: create container
      shell: docker container run -itd --name HED-container -p 9000:80 houssamed100/docker-project
